
import React from 'react';

const Footer: React.FC = () => {
  return (
    <footer className="text-center py-6 mt-12 border-t border-gray-800">
      <p className="text-gray-500">
        Guide generated by Google's Gemini API.
      </p>
    </footer>
  );
};

export default Footer;
